

name: node_app

on: # укажите сборку для запуска автоматического ci/cd
    push:
        branches:
            - "main"

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # укажите ОС для работы приложения
        steps:
            - # Клонируйте код приложения в ОС
                name: Checkout
                uses: actions/checkout@v3
            - # ввойдите в Docker Hub используя токен
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - # создайте экземпляр build kit builder
                name: Set up Docker Buildx
                uses: docker/build-push-action@v4
                with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
                  
